apiVersion: v1
kind: Pod
metadata:
  name: microservice-b
  labels:
    app: microservice-b
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'internal-app'
    vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/database/config'
    vault.hashicorp.com/agent-inject-template-database-config.txt: |
       {{- with secret "internal/data/database/config" -}}
          export password="{{ .Data.data.password }}"
          export username="{{ .Data.data.username }}"
       {{- end }}
    vault.hashicorp.com/agent-inject-file-database-config.txt: database-config.txt
spec:
  serviceAccountName: internal-app
  containers:
    - name: app
      image: samuelngarciar/bmspython:latest
      command: ["bash", "-c", "cat /vault/secrets/database-config.txt >> ~/.bashrc && source ~/.bashrc && python app.py"]
