apiVersion: v1
kind: Pod
metadata:
  name: microservice-a
  labels:
    app: microservice-a-with-annotations
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'microservices-role'
    vault.hashicorp.com/agent-inject-secret-credentials.txt: 'secret/data/microservices/secreto-a'
spec:
  serviceAccountName: internal-app
  containers:
    - name: app
      image: httpd
